apiVersion: kustomize.config.k8s.io/v1beta1
kind: Component

resources:
  - postgres-depl.yaml

secretGenerator:
  - name: postgres-creds
    literals:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    type: Opaque
patches:
  - path: deployment-patch.yaml
  - target:
      kind: Deployment
      name: db-deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0
        value:
          name: db
          image: mongo
