apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  org: "SARE CRAFT CODE"
namespace: lab
namePrefix: "sare-"
nameSuffix: "-code"
commonAnnotations:
  app: "sare-craft-code"
  version: "1.0.0"

images:
  - name: redis
    newTag: latest
resources:
  - api/
  - cache/
  - db/

patches:
  - target:
      kind: Deployment
      name: redis
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: add
        path: /spec/template/metadata/labels/org
        value: "SARE CRAFT CODE"
